// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0uQmSW1-v9GXJFHPGaduF7s7F5FXjcFk',
    appId: '1:539096927889:web:15be6363e4529412e23930',
    messagingSenderId: '539096927889',
    projectId: 'made-login-41383',
    authDomain: 'made-login-41383.firebaseapp.com',
    storageBucket: 'made-login-41383.firebasestorage.app',
    measurementId: 'G-FZQMQV411W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTrbz7EmdgO0YV2kpMNLxiGZKYasjDcJM',
    appId: '1:539096927889:android:54c1a886e575a66ae23930',
    messagingSenderId: '539096927889',
    projectId: 'made-login-41383',
    storageBucket: 'made-login-41383.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfe48AubOtY7eFWhF63yRW6fs0gBsAqeM',
    appId: '1:539096927889:ios:37b1d0a32479e309e23930',
    messagingSenderId: '539096927889',
    projectId: 'made-login-41383',
    storageBucket: 'made-login-41383.firebasestorage.app',
    iosBundleId: 'com.example.loginFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfe48AubOtY7eFWhF63yRW6fs0gBsAqeM',
    appId: '1:539096927889:ios:37b1d0a32479e309e23930',
    messagingSenderId: '539096927889',
    projectId: 'made-login-41383',
    storageBucket: 'made-login-41383.firebasestorage.app',
    iosBundleId: 'com.example.loginFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0uQmSW1-v9GXJFHPGaduF7s7F5FXjcFk',
    appId: '1:539096927889:web:bcb041ea1e4fc522e23930',
    messagingSenderId: '539096927889',
    projectId: 'made-login-41383',
    authDomain: 'made-login-41383.firebaseapp.com',
    storageBucket: 'made-login-41383.firebasestorage.app',
    measurementId: 'G-4RRKVR48TQ',
  );
}